### ISSUE TITLE
Cannot use generateNanoId() in Seeder

### ISSUE THREAD

**Issue by densat98** [yondifon/laravel-nanoid#5]
Can i use nanoid in Seeder?
Currently im using in model, but no idea how to use in Seeder 

Need solution for this..

Thanks you

**Comment by yondifon** [comment]
Yeah @densat98. You can. 

Use this class within your seeder class. 
https://github.com/yondifon/laravel-nanoid/blob/main/src/Eloquent/InteractsWithNanoid.php

**Comment by densat98** [comment]
Thank you @yondifon
