### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by pm-consultancy** [yondifon/laravel-nanoid#9]
Will this package be updated to support Laravel 11 ?

**Comment by yondifon** [comment]
Yes, I'll fix it later today 

🙏🏾

**Comment by elijahcruz12** [comment]
Bumping this to see about Laravel 11 support as well

**Comment by yondifon** [comment]
@elijahcruz12  @pm-consultancy 

Fixed. sorry it took a while
